# Generated by Django 4.2 on 2023-05-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('shares', models.DecimalField(decimal_places=3, max_digits=15)),
                ('averagePPS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalCostBasis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.broker')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.BooleanField()),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('shares', models.DecimalField(decimal_places=3, max_digits=15)),
                ('pricePerShare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costBasis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(max_length=100)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.broker')),
            ],
        ),
        migrations.DeleteModel(
            name='TeachBroker',
        ),
    ]
